version: '2'
volumes:
  api.openmsi-nersc:
    external: true
    driver: rancher-nfs
services:
  app:
    image: registry.spin.nersc.gov/canon/openmsi:dev
    cap_drop:
    - ALL
    stdin_open: true
    volumes:
    - /global/project/projectdirs/openmsi:/project:ro
    - api.openmsi-nersc:/data
    tty: true
    user: 55710:55809
    command:
    - /bin/bash
    labels:
      io.rancher.container.pull_image: always
  web:
    image: registry.spin.nersc.gov/canon/openmsi:dev
    environment:
      API_ROOT: https://openmsi.nersc.gov/
    cap_drop:
    - ALL
    volumes:
    - api.openmsi-nersc:/data
    - /global/project/projectdirs/openmsi/omsi_data:/data/openmsi/omsi_data:ro
    - /global/project/projectdirs/openmsi/:/project/projectdirs/openmsi/:ro
    tty: true
    ports:
    - 60003:8000/tcp
    user: 55710:55809
    labels:
      io.rancher.container.pull_image: always
  web-redirect:
    image: registry.spin.nersc.gov/metatlas/redirect
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  kv:
    cap_add:
    - CHOWN
    image: scanon/fixdir
    cap_drop:
    - ALL
    volumes:
    - api.openmsi-nersc:/data
    command:
    - '55710'
    - /data
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
