version: '2'
services:
  app:
    scale: 1
    start_on_create: true
  web:
    scale: 1
    start_on_create: true
  web-redirect:
    scale: 1
    start_on_create: true
  kv:
    scale: 1
    start_on_create: true
